networks:
  dev:


services:
#  api-pubsub-server:
#    build:
#      context: .
#      dockerfile: ./build/httpApp/Dockerfile
#    image: api-pubsub-server
#    deploy:
#      resources:
#        limits:
#          memory: 6G
#          cpus: '6.0'
#        reservations:
#          memory: 4G
#    container_name: api-pubsub-server
#    command: ["sh", "-c", "go run /usr/src/app/cmd/httpApp/main.go"]
#    ports:
#      - "8080:8080"
#    networks:
#      - dev

  grpc-pubsub-server:
    build:
      context: .
      dockerfile: ./build/grpcApp/Dockerfile
    image: grpc-pubsub-server
    container_name: grpc-pubsub-server
    command: [ "sh", "-c", "go run /usr/src/app/cmd/grpcApp/main.go" ]
    environment:
      - GRPC_PORT=${GRPC_PORT}
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    networks:
      - dev